name: bus
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.1.4
  flutter_redux: "^0.5.2"
  cupertino_icons: ^0.1.2
  geolocator: "^2.1.0"
  firebase_core: "0.2.5+1"
  firebase_database: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.6.1"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bus_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/bus_icon.png"
  adaptive_icon_background: "#FFFFFF00"
